#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PackStudy.Resource", IsApplication=true)]

namespace PackStudy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int courses_array = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int semesters_array = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int NavyBlue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CircleButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int newwolfhead = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080026
			public const int btnAddCourse = 2131230758;
			
			// aapt resource value: 0x7f08002a
			public const int btnClassMessages = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int btnCreateGoogleDoc = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int btnCreateStudyGroup = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int btnGenerateDoc = 2131230767;
			
			// aapt resource value: 0x7f080028
			public const int btnGoNext = 2131230760;
			
			// aapt resource value: 0x7f080015
			public const int btnLogin = 2131230741;
			
			// aapt resource value: 0x7f080021
			public const int btnNext = 2131230753;
			
			// aapt resource value: 0x7f080016
			public const int btnRegister = 2131230742;
			
			// aapt resource value: 0x7f080027
			public const int btnRemoveCourse = 2131230759;
			
			// aapt resource value: 0x7f08000d
			public const int btnSaveChanges = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int btnSelectStudents = 2131230737;
			
			// aapt resource value: 0x7f08001c
			public const int btnSend = 2131230748;
			
			// aapt resource value: 0x7f080001
			public const int btnSettings = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int btnUpdateProfilePic = 2131230732;
			
			// aapt resource value: 0x7f08001a
			public const int btnUpload = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int demoImageView = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int etConfirmPassword = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int etCurrentPassword = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int etDescription = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int etEditFirstName = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int etEditLastName = 2131230727;
			
			// aapt resource value: 0x7f08001f
			public const int etEmail = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int etFirstName = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int etLastName = 2131230750;
			
			// aapt resource value: 0x7f08000a
			public const int etNewPassword = 2131230730;
			
			// aapt resource value: 0x7f080020
			public const int etPassword = 2131230752;
			
			// aapt resource value: 0x7f08000f
			public const int image = 2131230735;
			
			// aapt resource value: 0x7f080018
			public const int llMessageBoard = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int myButton = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int myImageView = 2131230722;
			
			// aapt resource value: 0x7f08002d
			public const int scrollView1 = 2131230765;
			
			// aapt resource value: 0x7f080025
			public const int spinClasses = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int spinSemester = 2131230756;
			
			// aapt resource value: 0x7f08002e
			public const int ssll = 2131230766;
			
			// aapt resource value: 0x7f080017
			public const int svScroll = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int tvMessages = 2131230745;
			
			// aapt resource value: 0x7f080022
			public const int tvPromptErrors = 2131230754;
			
			// aapt resource value: 0x7f08000e
			public const int tvSavePrompt = 2131230734;
			
			// aapt resource value: 0x7f080004
			public const int txtEditFirstNamePrompt = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int txtEditLastNamePrompt = 2131230726;
			
			// aapt resource value: 0x7f080013
			public const int txtEmail = 2131230739;
			
			// aapt resource value: 0x7f08001b
			public const int txtMessage = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int txtMyAccountPrompt = 2131230723;
			
			// aapt resource value: 0x7f080014
			public const int txtPassword = 2131230740;
			
			// aapt resource value: 0x7f080023
			public const int txtSelectCoursePrompt = 2131230755;
			
			// aapt resource value: 0x7f080029
			public const int txtSelectedCourses = 2131230761;
			
			// aapt resource value: 0x7f080008
			public const int txtUpdatePasswordPrompt = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChangeUserPhoto = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditUserProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FullScreenImageView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int googleDocDescriptionLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MessageBoard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Registration = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SelectCourses = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int selectedClassHomePageLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectStudents = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int course_prompt = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int semester_prompt = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int DarkBlueTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int custom_CheckBoxStyle = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int custom_EditTextStyle = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int tvStyle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
